settings:
  pull_request:
    labels:
      - "files-sync"
    merge:
      mode: auto
      strategy: squash
      delete_branch: true

patterns:
  - files:
      - from: commons/.github
        to: .github

      - from: renovate-projects
        to: ./
        exclude:
          - files-sync-config.yaml

      - from: renovate-projects/.github
        to: .github

    repositories:
      - PrzemyslawSwiderski/printamos
      - PrzemyslawSwiderski/PrzemyslawSwiderski.github.io
      - PrzemyslawSwiderski/sdk-import-plugin
