settings:
  pull_request:
    labels:
      - "files-sync"
    merge:
      mode: immediate
      strategy: squash
      delete_branch: true

patterns:
  - files:
      - from: gradle-plugin-template
        to: ./
        exclude:
          - files-sync-config.yaml

      - from: gradle-plugin-template/.github
        to: .github

    delete_files:
      - .github/workflows/gradle-build.yml
      - .github/workflows/dependabot-auto-merge.yml
      - .github/workflows/auto-merge.yml
      - .github/dependabot.yml

    repositories:
      - PrzemyslawSwiderski/python-uv-gradle-plugin
