settings:
  pull_request:
    labels:
      - "files-sync"
    merge:
      mode: auto
      strategy: merge
      delete_branch: true

patterns:
  - files:
      - from: gradle-plugin-template
        to: ./
        exclude:
          - files-sync-config.yaml

      - from: gradle-plugin-template/.github
        to: .github

    delete_files:
      - .github/workflows/gradle-build.yml
      - .github/workflows/auto-merge.yml

    repositories:
      - PrzemyslawSwiderski/python-uv-gradle-plugin
