settings:
  pull_request:
    labels:
      - "files-sync"
    merge:
      mode: immediate
      strategy: squash
      delete_branch: true

patterns:
  - files:
      - from: commons/.github
        to: .github

      - from: gradle-plugins
        to: ./
        exclude:
          - files-sync-config.yaml

      - from: gradle-plugins/.github
        to: .github

    delete_files:
      - .github/workflows/gradle-build.yml
      - .github/workflows/dependabot-auto-merge.yml
      - .github/workflows/auto-merge.yml
      - .github/dependabot.yml
      - .github/workflows/post-release-updates.yml

    repositories:
      - PrzemyslawSwiderski/python-gradle-plugin
      - PrzemyslawSwiderski/python-uv-gradle-plugin
      - PrzemyslawSwiderski/terraform-gradle-plugin
      - PrzemyslawSwiderski/helm-gradle-plugin
      - PrzemyslawSwiderski/yaml-secrets-gradle-plugin
